package com.ezwel.htl.interfaces.server.entities;

import java.math.BigDecimal;

import org.apache.ibatis.type.Alias;

import com.ezwel.htl.interfaces.commons.annotation.APIFields;
import com.ezwel.htl.interfaces.commons.annotation.APIModel;
import com.ezwel.htl.interfaces.server.commons.abstracts.AbstractEntity;

/**
 * <b>History : Entity Code Generated By iCodeManager Made by API Team KSW</b>
 *
 * <pre>
 * 버전              성명                                일자                                       변경내용
 * -------    ----------------     -------------------		-----------------
 * 0.0.1      iCodeManager         2019-01-29 10:59:41      신규자동생성 
 * </pre>
 * 
 * @author developer
 * @since 2019-01-29 10:59:41
 * @version 0.0.1
 * @see "EZWEL Entity"
 */
//@Data
@Alias("ezcGuestRoom")
//@EqualsAndHashCode(callSuper=true)
@APIModel(modelNames="EZC 직영숙박 객실조회", description="EZC 직영숙박 객실조회 ( VT_GUEST_ROOM:코드생성용뷰 )", modelTypes="VIEW")
public class EzcGuestRoom extends AbstractEntity {

	
	@APIFields(description = "EZC 직영숙박 객실조회", maxLength=0)
	private String faclCd;

	@APIFields(description = "제휴사 코드", maxLength=0)
	private String partnerCd;

	@APIFields(description = "시설 코드", maxLength=0)
	private String roomNo;

	@APIFields(description = "객실상품코드", maxLength=0)
	private String roomName;

	@APIFields(description = "정상가", maxLength=22)
	private BigDecimal priceForList;

	@APIFields(description = "판매가", maxLength=22)
	private BigDecimal priceForSale;

	@APIFields(description = "기준인원", maxLength=22)
	private BigDecimal adtCntMin;

	@APIFields(description = "최대인원", maxLength=22)
	private BigDecimal adtCntMax;

	@APIFields(description = "객실정보", maxLength=0)
	private String roomInfo;

	@APIFields(description = "잔여객실수량", maxLength=22)
	private BigDecimal roomAvailCount;

	@APIFields(description = "확정예약여부코드", maxLength=0)
	private String rsvTypeCode;

	@APIFields(description = "조식포함여부", maxLength=0)
	private String breakfast;

	@APIFields(description = "특가상품여부", maxLength=0)
	private String spcType;

	@APIFields(description = "특가상품종료일시", maxLength=0)
	private String spcTypeTime;

	@APIFields(description = "객실수")
	private Integer roomCnt;
	
	@APIFields(description = "객실정보조회 Input 체크인", isDate=true, dateFormat="yyyyMMdd", required=true, maxLength=8)
	private String checkInDate;
	
	@APIFields(description = "객실정보조회 Input 체크아웃", isDate=true, dateFormat="yyyyMMdd", required=true, maxLength=8)
	private String checkOutDate;
	
	
	public String getFaclCd() {
		return faclCd;
	}

	public void setFaclCd(String faclCd) {
		this.faclCd = faclCd;
	}

	public String getPartnerCd() {
		return partnerCd;
	}

	public void setPartnerCd(String partnerCd) {
		this.partnerCd = partnerCd;
	}

	public String getRoomNo() {
		return roomNo;
	}

	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	public String getRoomName() {
		return roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	public BigDecimal getPriceForList() {
		return priceForList;
	}

	public void setPriceForList(BigDecimal priceForList) {
		this.priceForList = priceForList;
	}

	public BigDecimal getPriceForSale() {
		return priceForSale;
	}

	public void setPriceForSale(BigDecimal priceForSale) {
		this.priceForSale = priceForSale;
	}

	public BigDecimal getAdtCntMin() {
		return adtCntMin;
	}

	public void setAdtCntMin(BigDecimal adtCntMin) {
		this.adtCntMin = adtCntMin;
	}

	public BigDecimal getAdtCntMax() {
		return adtCntMax;
	}

	public void setAdtCntMax(BigDecimal adtCntMax) {
		this.adtCntMax = adtCntMax;
	}

	public String getRoomInfo() {
		return roomInfo;
	}

	public void setRoomInfo(String roomInfo) {
		this.roomInfo = roomInfo;
	}

	public BigDecimal getRoomAvailCount() {
		return roomAvailCount;
	}

	public void setRoomAvailCount(BigDecimal roomAvailCount) {
		this.roomAvailCount = roomAvailCount;
	}

	public String getRsvTypeCode() {
		return rsvTypeCode;
	}

	public void setRsvTypeCode(String rsvTypeCode) {
		this.rsvTypeCode = rsvTypeCode;
	}

	public String getBreakfast() {
		return breakfast;
	}

	public void setBreakfast(String breakfast) {
		this.breakfast = breakfast;
	}

	public String getSpcType() {
		return spcType;
	}

	public void setSpcType(String spcType) {
		this.spcType = spcType;
	}

	public String getSpcTypeTime() {
		return spcTypeTime;
	}

	public void setSpcTypeTime(String spcTypeTime) {
		this.spcTypeTime = spcTypeTime;
	}

	public Integer getRoomCnt() {
		return roomCnt;
	}

	public void setRoomCnt(Integer roomCnt) {
		this.roomCnt = roomCnt;
	}

	public String getCheckInDate() {
		return checkInDate;
	}

	public void setCheckInDate(String checkInDate) {
		this.checkInDate = checkInDate;
	}

	public String getCheckOutDate() {
		return checkOutDate;
	}

	public void setCheckOutDate(String checkOutDate) {
		this.checkOutDate = checkOutDate;
	}


}	
