package com.ezwel.htl.interfaces.server.commons.constants;

public class NamespaceConstants {

	public final static String OUTSIDE_MAPPER;
	public final static String IF_COMM_MAPPER;
	
	public final static String EZC_API_LOG_MAPPER;
	public final static String EZC_API_REQ_MAPPER;
	public final static String EZC_API_REQ_TEMPLATE_MAPPER;
	public final static String EZC_AREA_CD_MAPPER;
	public final static String EZC_AUTH_MAPPER;
	public final static String EZC_AUTH_GRP_MAPPER;
	public final static String EZC_AUTH_MAPPING_MAPPER;
	public final static String EZC_CACHE_DAY_PRICE_MAPPER;
	public final static String EZC_CACHE_DAY_PRICE_LOG_MAPPER;
	public final static String EZC_CACHE_MIN_AMT_MAPPER;
	public final static String EZC_CACHE_SEARCH_LOG_MAPPER;
	public final static String EZC_CHANNEL_BLACK_FACL_MAPPER;
	public final static String EZC_CHANNEL_CITYCD_MAPPER;
	public final static String EZC_CHANNEL_CLIENT_MAPPER;
	public final static String EZC_CHANNEL_CLIENT_PARTNER_MAPPER;
	public final static String EZC_CHANNEL_MNG_MAPPER;
	public final static String EZC_CHANNEL_PARTNER_MAPPER;
	public final static String EZC_CHANNEL_ROOM_TYPE_MAPPER;
	public final static String EZC_CITY_CD_MAPPER;
	public final static String EZC_CLASS_CD_MAPPER;
	public final static String EZC_CLIENT_INFO_MAPPER;
	public final static String EZC_CNCLIENT_BLACK_FACL_MAPPER;
	public final static String EZC_CNCLIENT_CITYCD_MAPPER;
	public final static String EZC_CNCLIENT_FACL_MARK_MAPPER;
	public final static String EZC_CNCLIENT_ROOM_TYPE_MAPPER;
	public final static String EZC_CPN_MAPPER;
	public final static String EZC_CPN_CHANNEL_MAPPER;
	public final static String EZC_CPN_CITY_MAPPER;
	public final static String EZC_CPN_CLIENT_MAPPER;
	public final static String EZC_CPN_FACL_MAPPER;
	public final static String EZC_CPN_PARTNER_MAPPER;
	public final static String EZC_CPN_ROOM_TYPE_MAPPER;
	public final static String EZC_CPN_USE_HIST_MAPPER;
	public final static String EZC_DEPOSIT_MAPPER;
	public final static String EZC_DEPOSIT_ISSUE_HIST_MAPPER;
	public final static String EZC_DEPOSIT_USE_HIST_MAPPER;
	public final static String EZC_DETAIL_CD_MAPPER;
	public final static String EZC_DISP_MAPPER;
	public final static String EZC_DIST_CANCEL_RULE_MAPPER;
	public final static String EZC_DIST_EVID_MAPPER;
	public final static String EZC_DIST_FACL_DETAIL_MAPPER;
	public final static String EZC_DIST_ROOM_MAPPER;
	public final static String EZC_DIST_ROOM_AMT_MAPPER;
	public final static String EZC_DIST_ROOM_OPT_MAPPER;
	public final static String EZC_FACL_MAPPER;
	public final static String EZC_FACL_AMENT_MAPPER;
	public final static String EZC_FACL_HIST_MAPPER;
	public final static String EZC_FACL_IMG_MAPPER;
	public final static String EZC_FACL_REVIEW_MAPPER;
	public final static String EZC_FACL_REVIEW_GRADE_MAPPER;
	public final static String EZC_FACL_REVIEW_IMG_MAPPER;
	public final static String EZC_FREQ_TXT_MAPPER;
	public final static String EZC_HOLIDAY_MAPPER;
	public final static String EZC_MAPPING_FACL_MAPPER;
	public final static String EZC_MAPPING_GRP_FACL_MAPPER;
	public final static String EZC_MEM_MAPPER;
	public final static String EZC_MENU_MAPPER;
	public final static String EZC_MGR_MAPPER;
	public final static String EZC_MGR_LOG_MAPPER;
	public final static String EZC_MGR_NOTICE_MAPPER;
	public final static String EZC_MGR_NOTICE_ATTACH_MAPPER;
	public final static String EZC_MY_CPN_MAPPER;
	public final static String EZC_PARTNER_MAPPER;
	public final static String EZC_PARTNER_EZWEL_MGR_MAPPER;
	public final static String EZC_POPUL_SEARCH_MAPPER;
	public final static String EZC_PRM_CHANNEL_MAPPER;
	public final static String EZC_PRM_CLIENT_MAPPER;
	public final static String EZC_PRM_COMMENT_MAPPER;
	public final static String EZC_PRM_CPN_MAPPER;
	public final static String EZC_PRM_GOODS_MAPPER;
	public final static String EZC_PRM_MNG_MAPPER;
	public final static String EZC_PRM_SURVEY_MAPPER;
	public final static String EZC_PRM_SURVEY_ANSWER_MAPPER;
	public final static String EZC_PRM_SURVEY_USER_MAPPER;
	public final static String EZC_PRM_TAB_MAPPER;
	public final static String EZC_QNA_MAPPER;
	public final static String EZC_RESERV_BASE_MAPPER;
	public final static String EZC_RESERV_CANCEL_MAPPER;
	public final static String EZC_RESERV_MNG_HIS_MAPPER;
	public final static String EZC_RESERV_PAY_MAPPER;
	public final static String EZC_RESERV_ROOM_MAPPER;
	public final static String EZC_RESERV_ROOM_OPT_MAPPER;
	public final static String EZC_RESERV_RULE_PENALTY_MAPPER;
	public final static String EZC_SPOT_MAPPER;
	public final static String EZC_SPOT_MAPPING_FACL_MAPPER;
	
	static {
		
		OUTSIDE_MAPPER = "com.ezwel.htl.interfaces.server.repository.outsideMapper";
		IF_COMM_MAPPER = "com.ezwel.htl.interfaces.server.repository.interfaceCommMapper";
		
		EZC_API_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcApiLogMapper";
		EZC_API_REQ_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcApiReqMapper";
		EZC_API_REQ_TEMPLATE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcApiReqTemplateMapper";
		EZC_AREA_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAreaCdMapper";
		EZC_AUTH_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAuthMapper";
		EZC_AUTH_GRP_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAuthGrpMapper";
		EZC_AUTH_MAPPING_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAuthMappingMapper";
		EZC_CACHE_DAY_PRICE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheDayPriceMapper";
		EZC_CACHE_DAY_PRICE_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheDayPriceLogMapper";
		EZC_CACHE_MIN_AMT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheMinAmtMapper";
		EZC_CACHE_SEARCH_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheSearchLogMapper";
		EZC_CHANNEL_BLACK_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelBlackFaclMapper";
		EZC_CHANNEL_CITYCD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelCitycdMapper";
		EZC_CHANNEL_CLIENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelClientMapper";
		EZC_CHANNEL_CLIENT_PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelClientPartnerMapper";
		EZC_CHANNEL_MNG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelMngMapper";
		EZC_CHANNEL_PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelPartnerMapper";
		EZC_CHANNEL_ROOM_TYPE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelRoomTypeMapper";
		EZC_CITY_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCityCdMapper";
		EZC_CLASS_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcClassCdMapper";
		EZC_CLIENT_INFO_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcClientInfoMapper";
		EZC_CNCLIENT_BLACK_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientBlackFaclMapper";
		EZC_CNCLIENT_CITYCD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientCitycdMapper";
		EZC_CNCLIENT_FACL_MARK_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientFaclMarkMapper";
		EZC_CNCLIENT_ROOM_TYPE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientRoomTypeMapper";
		EZC_CPN_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnMapper";
		EZC_CPN_CHANNEL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnChannelMapper";
		EZC_CPN_CITY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnCityMapper";
		EZC_CPN_CLIENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnClientMapper";
		EZC_CPN_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnFaclMapper";
		EZC_CPN_PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnPartnerMapper";
		EZC_CPN_ROOM_TYPE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnRoomTypeMapper";
		EZC_CPN_USE_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnUseHistMapper";
		EZC_DEPOSIT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDepositMapper";
		EZC_DEPOSIT_ISSUE_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDepositIssueHistMapper";
		EZC_DEPOSIT_USE_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDepositUseHistMapper";
		EZC_DETAIL_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDetailCdMapper";
		EZC_DISP_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDispMapper";
		EZC_DIST_CANCEL_RULE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistCancelRuleMapper";
		EZC_DIST_EVID_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistEvidMapper";
		EZC_DIST_FACL_DETAIL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistFaclDetailMapper";
		EZC_DIST_ROOM_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistRoomMapper";
		EZC_DIST_ROOM_AMT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistRoomAmtMapper";
		EZC_DIST_ROOM_OPT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistRoomOptMapper";
		EZC_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclMapper";
		EZC_FACL_AMENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclAmentMapper";
		EZC_FACL_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclHistMapper";
		EZC_FACL_IMG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclImgMapper";
		EZC_FACL_REVIEW_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewMapper";
		EZC_FACL_REVIEW_GRADE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewGradeMapper";
		EZC_FACL_REVIEW_IMG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewImgMapper";
		EZC_FREQ_TXT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFreqTxtMapper";
		EZC_HOLIDAY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcHolidayMapper";
		EZC_MAPPING_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMappingFaclMapper";
		EZC_MAPPING_GRP_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMappingGrpFaclMapper";
		EZC_MEM_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMemMapper";
		EZC_MENU_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMenuMapper";
		EZC_MGR_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrMapper";
		EZC_MGR_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrLogMapper";
		EZC_MGR_NOTICE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrNoticeMapper";
		EZC_MGR_NOTICE_ATTACH_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrNoticeAttachMapper";
		EZC_MY_CPN_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMyCpnMapper";
		EZC_PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPartnerMapper";
		EZC_PARTNER_EZWEL_MGR_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPartnerEzwelMgrMapper";
		EZC_POPUL_SEARCH_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPopulSearchMapper";
		EZC_PRM_CHANNEL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmChannelMapper";
		EZC_PRM_CLIENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmClientMapper";
		EZC_PRM_COMMENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmCommentMapper";
		EZC_PRM_CPN_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmCpnMapper";
		EZC_PRM_GOODS_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmGoodsMapper";
		EZC_PRM_MNG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmMngMapper";
		EZC_PRM_SURVEY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyMapper";
		EZC_PRM_SURVEY_ANSWER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyAnswerMapper";
		EZC_PRM_SURVEY_USER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyUserMapper";
		EZC_PRM_TAB_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmTabMapper";
		EZC_QNA_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcQnaMapper";
		EZC_RESERV_BASE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservBaseMapper";
		EZC_RESERV_CANCEL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservCancelMapper";
		EZC_RESERV_MNG_HIS_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservMngHisMapper";
		EZC_RESERV_PAY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservPayMapper";
		EZC_RESERV_ROOM_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservRoomMapper";
		EZC_RESERV_ROOM_OPT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservRoomOptMapper";
		EZC_RESERV_RULE_PENALTY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservRulePenaltyMapper";
		EZC_SPOT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcSpotMapper";
		EZC_SPOT_MAPPING_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcSpotMappingFaclMapper";		
	}
	
}
