package com.ezwel.htl.interfaces.server.commons.constants;

public class NamespaceConstants {

	public final static String OUTSIDE_MAPPER;
	public final static String IF_COMM_MAPPER;
	
	public final static String API_LOG_MAPPER;
	public final static String API_REQ_MAPPER;
	public final static String API_REQ_TEMPLATE_MAPPER;
	public final static String AREA_CD_MAPPER;
	public final static String AUTH_MAPPER;
	public final static String AUTH_GRP_MAPPER;
	public final static String AUTH_MAPPING_MAPPER;
	public final static String CACHE_DAY_PRICE_MAPPER;
	public final static String CACHE_DAY_PRICE_LOG_MAPPER;
	public final static String CACHE_MIN_AMT_MAPPER;
	public final static String CACHE_SEARCH_LOG_MAPPER;
	public final static String CHANNEL_BLACK_FACL_MAPPER;
	public final static String CHANNEL_CITYCD_MAPPER;
	public final static String CHANNEL_CLIENT_MAPPER;
	public final static String CHANNEL_CLIENT_PARTNER_MAPPER;
	public final static String CHANNEL_MNG_MAPPER;
	public final static String CHANNEL_PARTNER_MAPPER;
	public final static String CHANNEL_ROOM_TYPE_MAPPER;
	public final static String CITY_CD_MAPPER;
	public final static String CLASS_CD_MAPPER;
	public final static String CLIENT_INFO_MAPPER;
	public final static String CNCLIENT_BLACK_FACL_MAPPER;
	public final static String CNCLIENT_CITYCD_MAPPER;
	public final static String CNCLIENT_FACL_MARK_MAPPER;
	public final static String CNCLIENT_ROOM_TYPE_MAPPER;
	public final static String CPN_MAPPER;
	public final static String CPN_CHANNEL_MAPPER;
	public final static String CPN_CITY_MAPPER;
	public final static String CPN_CLIENT_MAPPER;
	public final static String CPN_FACL_MAPPER;
	public final static String CPN_PARTNER_MAPPER;
	public final static String CPN_ROOM_TYPE_MAPPER;
	public final static String CPN_USE_HIST_MAPPER;
	public final static String DEPOSIT_MAPPER;
	public final static String DEPOSIT_ISSUE_HIST_MAPPER;
	public final static String DEPOSIT_USE_HIST_MAPPER;
	public final static String DETAIL_CD_MAPPER;
	public final static String DISP_MAPPER;
	public final static String DIST_CANCEL_RULE_MAPPER;
	public final static String DIST_EVID_MAPPER;
	public final static String DIST_FACL_DETAIL_MAPPER;
	public final static String DIST_ROOM_MAPPER;
	public final static String DIST_ROOM_AMT_MAPPER;
	public final static String DIST_ROOM_OPT_MAPPER;
	public final static String FACL_MAPPER;
	public final static String FACL_AMENT_MAPPER;
	public final static String FACL_HIST_MAPPER;
	public final static String FACL_IMG_MAPPER;
	public final static String FACL_REVIEW_MAPPER;
	public final static String FACL_REVIEW_GRADE_MAPPER;
	public final static String FACL_REVIEW_IMG_MAPPER;
	public final static String FREQ_TXT_MAPPER;
	public final static String HOLIDAY_MAPPER;
	public final static String MAPPING_FACL_MAPPER;
	public final static String MAPPING_GRP_FACL_MAPPER;
	public final static String MEM_MAPPER;
	public final static String MENU_MAPPER;
	public final static String MGR_MAPPER;
	public final static String MGR_LOG_MAPPER;
	public final static String MGR_NOTICE_MAPPER;
	public final static String MGR_NOTICE_ATTACH_MAPPER;
	public final static String MY_CPN_MAPPER;
	public final static String PARTNER_MAPPER;
	public final static String PARTNER_EZWEL_MGR_MAPPER;
	public final static String POPUL_SEARCH_MAPPER;
	public final static String PRM_CHANNEL_MAPPER;
	public final static String PRM_CLIENT_MAPPER;
	public final static String PRM_COMMENT_MAPPER;
	public final static String PRM_CPN_MAPPER;
	public final static String PRM_GOODS_MAPPER;
	public final static String PRM_MNG_MAPPER;
	public final static String PRM_SURVEY_MAPPER;
	public final static String PRM_SURVEY_ANSWER_MAPPER;
	public final static String PRM_SURVEY_USER_MAPPER;
	public final static String PRM_TAB_MAPPER;
	public final static String QNA_MAPPER;
	public final static String RESERV_BASE_MAPPER;
	public final static String RESERV_CANCEL_MAPPER;
	public final static String RESERV_MNG_HIS_MAPPER;
	public final static String RESERV_PAY_MAPPER;
	public final static String RESERV_ROOM_MAPPER;
	public final static String RESERV_ROOM_OPT_MAPPER;
	public final static String RESERV_RULE_PENALTY_MAPPER;
	public final static String SPOT_MAPPER;
	public final static String SPOT_MAPPING_FACL_MAPPER;
	
	static {
<<<<<<< HEAD
		
		OUTSIDE_MAPPER = "com.ezwel.htl.interfaces.server.repository.outsideMapper";
		IF_COMM_MAPPER = "com.ezwel.htl.interfaces.server.repository.interfaceCommMapper";
		
		API_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcApiLogMapper";
		API_REQ_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcApiReqMapper";
		API_REQ_TEMPLATE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcApiReqTemplateMapper";
		AREA_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAreaCdMapper";
		AUTH_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAuthMapper";
		AUTH_GRP_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAuthGrpMapper";
		AUTH_MAPPING_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcAuthMappingMapper";
		CACHE_DAY_PRICE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheDayPriceMapper";
		CACHE_DAY_PRICE_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheDayPriceLogMapper";
		CACHE_MIN_AMT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheMinAmtMapper";
		CACHE_SEARCH_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCacheSearchLogMapper";
		CHANNEL_BLACK_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelBlackFaclMapper";
		CHANNEL_CITYCD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelCitycdMapper";
		CHANNEL_CLIENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelClientMapper";
		CHANNEL_CLIENT_PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelClientPartnerMapper";
		CHANNEL_MNG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelMngMapper";
		CHANNEL_PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelPartnerMapper";
		CHANNEL_ROOM_TYPE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcChannelRoomTypeMapper";
		CITY_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCityCdMapper";
		CLASS_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcClassCdMapper";
		CLIENT_INFO_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcClientInfoMapper";
		CNCLIENT_BLACK_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientBlackFaclMapper";
		CNCLIENT_CITYCD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientCitycdMapper";
		CNCLIENT_FACL_MARK_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientFaclMarkMapper";
		CNCLIENT_ROOM_TYPE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCnclientRoomTypeMapper";
		CPN_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnMapper";
		CPN_CHANNEL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnChannelMapper";
		CPN_CITY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnCityMapper";
		CPN_CLIENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnClientMapper";
		CPN_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnFaclMapper";
		CPN_PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnPartnerMapper";
		CPN_ROOM_TYPE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnRoomTypeMapper";
		CPN_USE_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcCpnUseHistMapper";
		DEPOSIT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDepositMapper";
		DEPOSIT_ISSUE_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDepositIssueHistMapper";
		DEPOSIT_USE_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDepositUseHistMapper";
		DETAIL_CD_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDetailCdMapper";
		DISP_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDispMapper";
		DIST_CANCEL_RULE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistCancelRuleMapper";
		DIST_EVID_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistEvidMapper";
		DIST_FACL_DETAIL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistFaclDetailMapper";
		DIST_ROOM_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistRoomMapper";
		DIST_ROOM_AMT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistRoomAmtMapper";
		DIST_ROOM_OPT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcDistRoomOptMapper";
		FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclMapper";
		FACL_AMENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclAmentMapper";
		FACL_HIST_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclHistMapper";
		FACL_IMG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclImgMapper";
		FACL_REVIEW_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewMapper";
		FACL_REVIEW_GRADE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewGradeMapper";
		FACL_REVIEW_IMG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewImgMapper";
		FREQ_TXT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcFreqTxtMapper";
		HOLIDAY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcHolidayMapper";
		MAPPING_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMappingFaclMapper";
		MAPPING_GRP_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMappingGrpFaclMapper";
		MEM_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMemMapper";
		MENU_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMenuMapper";
		MGR_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrMapper";
		MGR_LOG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrLogMapper";
		MGR_NOTICE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrNoticeMapper";
		MGR_NOTICE_ATTACH_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMgrNoticeAttachMapper";
		MY_CPN_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcMyCpnMapper";
		PARTNER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPartnerMapper";
		PARTNER_EZWEL_MGR_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPartnerEzwelMgrMapper";
		POPUL_SEARCH_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPopulSearchMapper";
		PRM_CHANNEL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmChannelMapper";
		PRM_CLIENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmClientMapper";
		PRM_COMMENT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmCommentMapper";
		PRM_CPN_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmCpnMapper";
		PRM_GOODS_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmGoodsMapper";
		PRM_MNG_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmMngMapper";
		PRM_SURVEY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyMapper";
		PRM_SURVEY_ANSWER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyAnswerMapper";
		PRM_SURVEY_USER_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyUserMapper";
		PRM_TAB_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcPrmTabMapper";
		QNA_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcQnaMapper";
		RESERV_BASE_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservBaseMapper";
		RESERV_CANCEL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservCancelMapper";
		RESERV_MNG_HIS_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservMngHisMapper";
		RESERV_PAY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservPayMapper";
		RESERV_ROOM_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservRoomMapper";
		RESERV_ROOM_OPT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservRoomOptMapper";
		RESERV_RULE_PENALTY_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcReservRulePenaltyMapper";
		SPOT_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcSpotMapper";
		SPOT_MAPPING_FACL_MAPPER = "com.ezwel.htl.interfaces.server.repository.EzcSpotMappingFaclMapper";		
=======
		NAMESPACE_MAP = new HashMap<String, String>();

		//NAMESPACE_MAP.put("OUTSIDE_MAPPER", "com.ezwel.htl.interfaces.server.repository.outsideMapper");
		//NAMESPACE_MAP.put("IF_COMM_MAPPER", "com.ezwel.htl.interfaces.server.repository.interfaceCommMapper");
		NAMESPACE_MAP.put("SEQUNCE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcSequnceMapper");
		NAMESPACE_MAP.put("API_LOG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcApiLogMapper");
		NAMESPACE_MAP.put("API_REQ_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcApiReqMapper");
		NAMESPACE_MAP.put("API_REQ_TEMPLATE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcApiReqTemplateMapper");
		NAMESPACE_MAP.put("AREA_CD_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcAreaCdMapper");
		NAMESPACE_MAP.put("AUTH_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcAuthMapper");
		NAMESPACE_MAP.put("AUTH_GRP_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcAuthGrpMapper");
		NAMESPACE_MAP.put("AUTH_MAPPING_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcAuthMappingMapper");
		NAMESPACE_MAP.put("CACHE_DAY_PRICE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCacheDayPriceMapper");
		NAMESPACE_MAP.put("CACHE_DAY_PRICE_LOG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCacheDayPriceLogMapper");
		NAMESPACE_MAP.put("CACHE_MIN_AMT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCacheMinAmtMapper");
		NAMESPACE_MAP.put("CACHE_SEARCH_LOG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCacheSearchLogMapper");
		NAMESPACE_MAP.put("CHANNEL_BLACK_FACL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcChannelBlackFaclMapper");
		NAMESPACE_MAP.put("CHANNEL_CITYCD_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcChannelCitycdMapper");
		NAMESPACE_MAP.put("CHANNEL_CLIENT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcChannelClientMapper");
		NAMESPACE_MAP.put("CHANNEL_CLIENT_PARTNER_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcChannelClientPartnerMapper");
		NAMESPACE_MAP.put("CHANNEL_MNG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcChannelMngMapper");
		NAMESPACE_MAP.put("CHANNEL_PARTNER_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcChannelPartnerMapper");
		NAMESPACE_MAP.put("CHANNEL_ROOM_TYPE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcChannelRoomTypeMapper");
		NAMESPACE_MAP.put("CITY_CD_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCityCdMapper");
		NAMESPACE_MAP.put("CLASS_CD_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcClassCdMapper");
		NAMESPACE_MAP.put("CLIENT_INFO_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcClientInfoMapper");
		NAMESPACE_MAP.put("CNCLIENT_BLACK_FACL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCnclientBlackFaclMapper");
		NAMESPACE_MAP.put("CNCLIENT_CITYCD_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCnclientCitycdMapper");
		NAMESPACE_MAP.put("CNCLIENT_FACL_MARK_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCnclientFaclMarkMapper");
		NAMESPACE_MAP.put("CNCLIENT_ROOM_TYPE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCnclientRoomTypeMapper");
		NAMESPACE_MAP.put("CPN_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnMapper");
		NAMESPACE_MAP.put("CPN_CHANNEL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnChannelMapper");
		NAMESPACE_MAP.put("CPN_CITY_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnCityMapper");
		NAMESPACE_MAP.put("CPN_CLIENT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnClientMapper");
		NAMESPACE_MAP.put("CPN_FACL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnFaclMapper");
		NAMESPACE_MAP.put("CPN_PARTNER_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnPartnerMapper");
		NAMESPACE_MAP.put("CPN_ROOM_TYPE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnRoomTypeMapper");
		NAMESPACE_MAP.put("CPN_USE_HIST_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcCpnUseHistMapper");
		NAMESPACE_MAP.put("DEPOSIT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDepositMapper");
		NAMESPACE_MAP.put("DEPOSIT_ISSUE_HIST_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDepositIssueHistMapper");
		NAMESPACE_MAP.put("DEPOSIT_USE_HIST_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDepositUseHistMapper");
		NAMESPACE_MAP.put("DETAIL_CD_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDetailCdMapper");
		NAMESPACE_MAP.put("DISP_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDispMapper");
		NAMESPACE_MAP.put("DIST_CANCEL_RULE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDistCancelRuleMapper");
		NAMESPACE_MAP.put("DIST_EVID_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDistEvidMapper");
		NAMESPACE_MAP.put("DIST_FACL_DETAIL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDistFaclDetailMapper");
		NAMESPACE_MAP.put("DIST_ROOM_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDistRoomMapper");
		NAMESPACE_MAP.put("DIST_ROOM_AMT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDistRoomAmtMapper");
		NAMESPACE_MAP.put("DIST_ROOM_OPT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcDistRoomOptMapper");
		NAMESPACE_MAP.put("FACL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFaclMapper");
		NAMESPACE_MAP.put("FACL_AMENT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFaclAmentMapper");
		NAMESPACE_MAP.put("FACL_HIST_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFaclHistMapper");
		NAMESPACE_MAP.put("FACL_IMG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFaclImgMapper");
		NAMESPACE_MAP.put("FACL_REVIEW_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewMapper");
		NAMESPACE_MAP.put("FACL_REVIEW_GRADE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewGradeMapper");
		NAMESPACE_MAP.put("FACL_REVIEW_IMG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFaclReviewImgMapper");
		NAMESPACE_MAP.put("FREQ_TXT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcFreqTxtMapper");
		NAMESPACE_MAP.put("HOLIDAY_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcHolidayMapper");
		NAMESPACE_MAP.put("MAPPING_FACL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMappingFaclMapper");
		NAMESPACE_MAP.put("MAPPING_GRP_FACL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMappingGrpFaclMapper");
		NAMESPACE_MAP.put("MEM_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMemMapper");
		NAMESPACE_MAP.put("MENU_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMenuMapper");
		NAMESPACE_MAP.put("MGR_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMgrMapper");
		NAMESPACE_MAP.put("MGR_LOG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMgrLogMapper");
		NAMESPACE_MAP.put("MGR_NOTICE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMgrNoticeMapper");
		NAMESPACE_MAP.put("MGR_NOTICE_ATTACH_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMgrNoticeAttachMapper");
		NAMESPACE_MAP.put("MY_CPN_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcMyCpnMapper");
		NAMESPACE_MAP.put("PARTNER_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPartnerMapper");
		NAMESPACE_MAP.put("PARTNER_EZWEL_MGR_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPartnerEzwelMgrMapper");
		NAMESPACE_MAP.put("POPUL_SEARCH_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPopulSearchMapper");
		NAMESPACE_MAP.put("PRM_CHANNEL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmChannelMapper");
		NAMESPACE_MAP.put("PRM_CLIENT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmClientMapper");
		NAMESPACE_MAP.put("PRM_COMMENT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmCommentMapper");
		NAMESPACE_MAP.put("PRM_CPN_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmCpnMapper");
		NAMESPACE_MAP.put("PRM_GOODS_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmGoodsMapper");
		NAMESPACE_MAP.put("PRM_MNG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmMngMapper");
		NAMESPACE_MAP.put("PRM_SURVEY_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyMapper");
		NAMESPACE_MAP.put("PRM_SURVEY_ANSWER_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyAnswerMapper");
		NAMESPACE_MAP.put("PRM_SURVEY_USER_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmSurveyUserMapper");
		NAMESPACE_MAP.put("PRM_TAB_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcPrmTabMapper");
		NAMESPACE_MAP.put("QNA_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcQnaMapper");
		NAMESPACE_MAP.put("RESERV_BASE_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcReservBaseMapper");
		NAMESPACE_MAP.put("RESERV_CANCEL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcReservCancelMapper");
		NAMESPACE_MAP.put("RESERV_MNG_HIS_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcReservMngHisMapper");
		NAMESPACE_MAP.put("RESERV_PAY_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcReservPayMapper");
		NAMESPACE_MAP.put("RESERV_ROOM_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcReservRoomMapper");
		NAMESPACE_MAP.put("RESERV_ROOM_OPT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcReservRoomOptMapper");
		NAMESPACE_MAP.put("RESERV_RULE_PENALTY_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcReservRulePenaltyMapper");
		NAMESPACE_MAP.put("SPOT_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcSpotMapper");
		NAMESPACE_MAP.put("SPOT_MAPPING_FACL_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcSpotMappingFaclMapper");
		NAMESPACE_MAP.put("IF_LOG_MAPPER", "com.ezwel.htl.interfaces.server.repository.EzcIfLogMapper");
>>>>>>> branch 'master' of https://github.com/ezwelapi/ezwel-api
	}
	
}
